#Examples of config settings
#===========================
#Uncomment the example that you want to run
#Leave the first two lines of the example commented, though
#The second line of each example provides the command for the terminal

#Example 1
#smt run --config .config.yaml -X data/X_train.npy -a fit_transform
#module: ml_project.models.feature_selection
#class: RandomSelection
#params:
#  n_components: 1000
#  random_state: 37

#Example Benno
#module: ml_project.models.feature_selection
#class: SliceHistogram
#params:
#   n_slices: 20
#   n_bins: 10

#Example 2 (Warning: might exceed your memory)
#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#module: ml_project.models.regression
#class: KernelEstimator

#Example 3
#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#module: ml_project.pipeline
#class: Pipeline
#params:
#  class_list:
#    - module: ml_project.models.feature_selection
#      class: SliceHistograms
#      params:
#        n_slices: 50
#        n_bins: 20
#    - module: sklearn.linear_model
#      class: LinearRegression

#Example 4
#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
#module: ml_project.model_selection
#class: GridSearchCV
#params:
#  est_module: ml_project.pipeline
#  est_class: Pipeline
#  est_params:
#    - module: ml_project.models.feature_selection
#      class: RandomSelection
#      params:
#        random_state: 37
#    - module: sklearn.linear_model
#      class: LinearRegression
#  param_grid:
#    RandomSelection__n_components:
#      - 55000
#      - 60000
#      - 65000
#  cv:
#    module: sklearn.model_selection
#    class: KFold
#    params:
#      n_splits: 3
#      shuffle: True
#      random_state: 37

#Score 55 submission
#smt run --config .config.yaml -X data/X_train.npy -y data/y_1.csv -a fit
module: ml_project.model_selection
class: GridSearchCV
params:
  est_module: ml_project.pipeline
  est_class: Pipeline
  est_params:
    - module: ml_project.models.feature_selection
      class: SliceHistograms 
    - module: sklearn.linear_model
      class: LinearRegression
  param_grid:
    SliceHistograms__n_slices:
      - 80
      - 120
      - 160
  cv:
    module: sklearn.model_selection
    class: KFold
    params:
      n_splits: 3
      shuffle: True
      random_state: 37
